### ISSUE TITLE
Does it deletes messenge from my side or bith sides.

### ISSUE THREAD

**Issue by Zahid01711** [Prabesh01/fb-message-delete-automation#2]
Well i have seen alot of things where you unsend the message also delete the message that i got, so i dont want that i only want to unsend my messages  and keep the message that i received.

**Comment by Prabesh01** [comment]
Sorry to inform you that this script no longer works. I have clearly mentioned it in the README file.

Yup, when the script used to work, we could choose weather to delete messages of both sides, or just mine or just theirs. You can see that in demo image: https://raw.githubusercontent.com/Prabesh01/fb-message-delete-automation/main/demo.png
(See the info provided after running the script in the image)

Also, I will love to hear from you if you have some information or idea regarding this script so that we could make it work again.

Thanks :)
